on:
  workflow_dispatch:
  push:
    paths:
      - 'bot/**'
      - '.github/workflows/deploy_bot.yml'

name: Build and push Docker image
jobs:
    deploy-container:
      runs-on: ubuntu-latest

      permissions:
        contents: read
        packages: write

      steps:
        - uses: actions/checkout@v3

        - name: Update cookie.txt
          shell: python
          run: |
            with open("bot/cookie.txt") as f:
              newText = '${{ secrets.YOUTUBE_COOKIE }}'
          
            with open("bot/cookie.txt", "w") as f:
                f.write(newText)

        - name: Log in to container registry
          uses: docker/login-action@v2
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Build and push Docker image
          uses: docker/build-push-action@v4
          with:
            context: ./bot
            file: ./bot/Dockerfile
            push: true
            tags: ghcr.io/${{ github.repository_owner }}/discord-music-bot:latest

        - name: Delete all packages but last
          uses: actions/delete-package-versions@v4
          with:
            package-name: discord-music-bot
            package-type: container
            min-versions-to-keep: 1
