on:
  push:
    paths:
      - 'activator/**'
      - '.github/workflows/deploy_activator.yml'

name: Build and push Cloudflare Worker
jobs:
  deploy-worker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update wrangler.toml
        shell: python
        run: |
          with open("activator/wrangler.toml") as f:
            newText = f.read().replace('<YOUR_KV_ACCOUNT_ID>', '${{ secrets.CLOUDFLARE_KV_ID }}')
        
          with open("activator/wrangler.toml", "w") as f:
              f.write(newText)

      - uses: cloudflare/wrangler-action@v3
        with:
          workingDirectory: activator
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          secrets: |
            AZURE_TENANT_ID
            AZURE_SUBSCRIPTION_ID
            AZURE_CLIENT_ID
            AZURE_CLIENT_SECRET
            AZURE_RESOURCE_GROUP
            AZURE_CONTAINER_NAME
            DISCORD_REQUEST_COMMAND_NAME
        env:
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
          AZURE_CONTAINER_NAME: ${{ secrets.AZURE_CONTAINER_NAME }}
          DISCORD_REQUEST_COMMAND_NAME: ${{ secrets.DISCORD_REQUEST_COMMAND_NAME }}

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm ci
        working-directory: ./activator

      - run: npm run publish
        working-directory: ./activator
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
